##===- projects/hw1part1/tools/hw1part1/Makefile ---------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
LEVEL=../..

#
# Give the name of the tool.
#
TOOLNAME=Hw1part1

#
# List libraries that we'll need
# We use LIBS because hw1part1 is a dynamic library.
#
USEDLIBS = hw1part1.a

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common

