##===- projects/hw1part1/tools/Makefile ----------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
DIRS=

include $(LEVEL)/Makefile.common
